name: Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  check-version:
    runs-on: ubuntu-latest

    outputs:
      should_publish: ${{ steps.version.outputs.should_publish }}
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: version
        run: |
          PREVIOUS_VERSION=$(git show HEAD^:package.json | grep '"version"' | awk -F '"' '{print $4}')
          CURRENT_VERSION=$(git show HEAD:package.json | grep '"version"' | awk -F '"' '{print $4}')

          echo "version=$CURRENT_VERSION" >> "${GITHUB_OUTPUT}"
          echo "tag=v$CURRENT_VERSION" >> "${GITHUB_OUTPUT}"

          if [[ "${CURRENT_VERSION}" != "${PREVIOUS_VERSION}" ]]; then
            echo "should_publish=true" >> "${GITHUB_OUTPUT}"
          else
            echo "should_publish=false" >> "${GITHUB_OUTPUT}"
          fi

  npm-publish:
    runs-on: ubuntu-latest

    needs: check-version

    if: needs.check-version.outputs.should_publish == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 24
          registry-url: https://registry.npmjs.org
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          pnpm publish

  github-packages:
    runs-on: ubuntu-latest

    needs: check-version

    if: needs.check-version.outputs.should_publish == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          npm publish

  tagging:
    runs-on: ubuntu-latest

    needs:
      - check-version
      - npm-publish
      - github-packages

    if: needs.check-version.outputs.should_publish == 'true'

    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4
      - id: tag
        run: |
          tag=${{ needs.check-version.outputs.tag }}
          git tag $tag
          git push origin $tag
          echo "tag=$tag" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest

    needs:
      - npm-publish
      - github-packages
      - tagging

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 24

      - name: Build dist
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Package release assets
        run: |
          tar -czf dist.tar.gz dist
          tar -czf vendor.tar.gz vendor

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tagging.outputs.tag }}
          release_name: ${{ needs.tagging.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload dist asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.tar.gz
          asset_name: dist.tar.gz
          asset_content_type: application/gzip

      - name: Upload vendor asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vendor.tar.gz
          asset_name: vendor.tar.gz
          asset_content_type: application/gzip
